name: After merge build

on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane
  schedule:
    - cron: '0 3 * * 1,4'

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          gradle-distribution-sha-256-sum-warning: false

      - name: Assemble
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Assemble
        env:
          WYKOP_KEYSTORE_KEY_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_KEY_PASSWORD }}
          WYKOP_KEYSTORE_KEY_NAME: ${{ secrets.WYKOP_KEYSTORE_KEY_NAME }}
          WYKOP_KEYSTORE_PASSWORD: ${{ secrets.WYKOP_KEYSTORE_PASSWORD }}
        run: ./gradlew app:assembleReleaseTestAndroidTest -PtestBuildType=releaseTest

      - name: Unit tests
        run: ./gradlew projectCoverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/cache@v2
        name: Upload base (release)
        with:
          path: |
            diffuse-source-file-release
            diffuse-mapping-file-release
          key: diffuse-${{ github.sha }}-${{ hashFiles('**/apk/debug/**.apk') }}

      - run: cp app/build/outputs/apk/release/app-release.apk diffuse-source-file-release
        shell: bash

      - run: cp app/build/outputs/mapping/release/mapping.txt diffuse-mapping-file-release
        shell: bash
